- name: Autodetecting Image Archive
  hosts: all
  become: yes
  tasks:
    - name: Ansible check file exists.
      stat:
        path: "{{ image-archive-path }}"
      register: p
    - name: Image Archive Found. Loading Images.
      command: "podman load -i {{ image-archive-path }}"
      when: p.stat.exists
